### ISSUE TITLE
DataTable issue. Sorting and Filtering are not working when multiselect mode is on.

### ISSUE THREAD

**Issue by YurinM** [TeamDev-Ltd/OpenFaces#116]
When multi select true and initial select service not present sorting and filtering are not working.

**Comment by YurinM** [comment]
Verified with: openfaces v2.1, browsers:  IE8 and IE11 - Can`t reproduce.
Created DataTable with paginator on more than 300 pages, and 25 rows on the page. When I selected 20 rows, filtering and sorting are working fine.

**Comment by YogeshTieto** [comment]
Try below steps
1. selection mode set to multiselect
2. Don't select any row
3. Turn on filtering 
4. Now put some valid data into filter field

**Comment by YurinM** [comment]
Verified by proposed steps, in next browsers: IE8, IE10/IE11 (document mode IE8) - issue don`t reproduced.
I wondered if you`re can provide me a standalone application or xhtml code samples for testing.

**Comment by YogeshTieto** [comment]
Long back i have posted this on openfaces-forum and you accepted this bug

![image](https://cloud.githubusercontent.com/assets/10973767/8354099/dab6992a-1b62-11e5-9e57-5a46c1816b9d.png)


Also below is the stack trace::


java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.RangeCheck(ArrayList.java:546)
	at java.util.ArrayList.get(ArrayList.java:321)
	at org.openfaces.component.table.MultipleRowSelection.getFirstSelectedRowData(MultipleRowSelection.java:293)
	at org.openfaces.component.table.DataTable.beforeRenderResponse(DataTable.java:244)
	at org.openfaces.component.table.DataTable.encodeBegin(DataTable.java:287)
	at org.openfaces.ajax.CommonAjaxViewRoot.renderSimpleUpdate(CommonAjaxViewRoot.java:1063)
	at org.openfaces.ajax.CommonAjaxViewRoot.ajaxRenderResponse(CommonAjaxViewRoot.java:970)
	at org.openfaces.ajax.CommonAjaxViewRoot.finishProcessAjaxRequest(CommonAjaxViewRoot.java:866)
	at org.openfaces.ajax.CommonAjaxViewRoot.doEncodeChildren(CommonAjaxViewRoot.java:474)
	at org.openfaces.ajax.CommonAjaxViewRoot.encodeChildren(CommonAjaxViewRoot.java:242)
	at org.openfaces.ajax.richfaces.A4JAjaxViewRoot.encodeChildren(A4JAjaxViewRoot.java:125)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:930)

**Comment by YurinM** [comment]
Thank you for the update.
As I can see, you use `richfaces.A4JAjax`. Do you have the same problem with openfaces ajax?

Also provide please browser version, where i could reproduce this problem.
