### ISSUE TITLE
Problem with filter in datatable

### ISSUE THREAD

**Issue by ramirescm** [TeamDev-Ltd/OpenFaces#98]
when i use   <o:inputTextFilter expression="#{row.stringField1}"/>  in datatable is throw java.lang.IllegalStateException

- OpenFaces 3.0
- Wildfly 8.2.0

Caused by: java.lang.IllegalStateException: TextSearchFilter should have exactly one child component - the search component. children.size = 0
    at org.openfaces.component.filter.TextSearchFilter.getSearchComponent(TextSearchFilter.java:46) [openfaces-3.0.jar:3.0.0]
    at org.openfaces.renderkit.filter.TextSearchFilterRenderer.decode(TextSearchFilterRenderer.java:66) [openfaces-3.0.jar:3.0.0]
    at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:831) [jboss-jsf-api_2.2_spec-2.2.8.jar:2.2.8]
    at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1226) [jboss-jsf-api_2.2_spec-2.2.8.jar:2.2.8]
    at org.openfaces.component.OUIData.process(OUIData.java:959) [openfaces-3.0.jar:3.0.0]
    at org.openfaces.component.OUIData.processColumnFacets(OUIData.java:853) [openfaces-3.0.jar:3.0.0]
    at org.openfaces.component.OUIData.processDecodes(OUIData.java:766) [openfaces-3.0.jar:3.0.0]
    at org.openfaces.component.table.AbstractTable.processDecodes(AbstractTable.java:966) [openfaces-3.0.jar:3.0.0]
    at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1221) [jboss-jsf-api_2.2_spec-2.2.8.jar:2.2.8]
    at javax.faces.component.UIForm.processDecodes(UIForm.java:225) [jboss-jsf-api_2.2_spec-2.2.8.jar:2.2.8]
    at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1221) [jboss-jsf-api_2.2_spec-2.2.8.jar:2.2.8]
    at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1221) [jboss-jsf-api_2.2_spec-2.2.8.jar:2.2.8]
    at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:929) [jboss-jsf-api_2.2_spec-2.2.8.jar:2.2.8]
    at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:78) [jsf-impl-2.2.8-jbossorg-1.jar:]
    at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) [jsf-impl-2.2.8-jbossorg-1.jar:]
    at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198) [jsf-impl-2.2.8-jbossorg-1.jar:]
    at org.apache.deltaspike.jsf.impl.listener.request.DeltaSpikeLifecycleWrapper.execute(DeltaSpikeLifecycleWrapper.java:89) [deltaspike-jsf-module-impl-1.0.2.jar:1.0.2]
    at javax.faces.lifecycle.LifecycleWrapper.execute(LifecycleWrapper.java:77) [jboss-jsf-api_2.2_spec-2.2.8.jar:2.2.8]
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646) [jboss-jsf-api_2.2_spec-2.2.8.jar:2.2.8]
    ... 47 more

**Comment by RomanPerin** [comment]
Hi Ramirescm!

I have checked InputTextFilter component. It works fine. 
So, could you provide a simple application and steps to reproduce this issue.

**Comment by ramirescm** [comment]
Hi RomanPerin

I posted the example code in http://stackoverflow.com/questions/28795117/caused-by-java-lang-illegalstateexception-textsearchfilter-should-have-exactly

**Comment by RomanPerin** [comment]
Hi!
I use Mojarra 2.1.12 and Tomcat 6.0.41.

What version of Mojarra do you use?

**Comment by ramirescm** [comment]
I use Mojarra 2.2.8 and Wildfly 8.2.0 .. I found this link in documentation.. https://sites.google.com/a/teamdev.com/openfaces-support/updates/openfaces30releasenotes

**Comment by RomanPerin** [comment]
Hi!
Try to use Mojarra versions earlier than 2.2.8.
If this doesn't help, please send a simple war file where the problem can be reproduced.
